In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode Gender column
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# one hot encode Geography column
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_df = pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('artifacts/regression/label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('artifacts/regression/onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('artifacts/regression/scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [13]:
## build the ANN regression model
model = Sequential([
    Input(shape=(X_train.shape[1],)),  # Explicit Input layer
    Dense(64, activation='relu'),      # HL1
    Dense(32, activation='relu'),      # HL2
    Dense(1)     # Output layer for regression
])

## compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regression_logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100397.2031 - mae: 100397.2031 - val_loss: 98586.2500 - val_mae: 98586.2500
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99837.3984 - mae: 99837.3984 - val_loss: 97415.7422 - val_mae: 97415.7422
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97726.3047 - mae: 97726.3047 - val_loss: 94237.5938 - val_mae: 94237.5938
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93341.1875 - mae: 93341.1875 - val_loss: 88695.9453 - val_mae: 88695.9453
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 86705.4766 - mae: 86705.4766 - val_loss: 81244.9531 - val_mae: 81244.9531
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 78551.5156 - mae: 78551.5156 - val_loss: 72860.3750 - val_mae: 72860.3750
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 70057.7031 - mae: 70057.7031 - val_loss: 65058.6250 - val_mae: 65058.6250
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62511.6797 - mae: 62511.6797 - val_loss: 58766.0195 - val_mae: 58766.0195
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 56981.7578 - mae: 56981.7578 - val_loss: 54635.1953 - val_mae: 54635.1953
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53532.3555 - mae: 53532.3555 - val_loss: 52216.6602 - val_mae: 52216.6602
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51747.6797 - mae: 51747.6797 - val_loss: 51235.6953 - val_mae: 51235.6953
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50957.2930 - mae: 50957.2930 - val_loss: 50896.6094 - val_mae: 50896.6094
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50611.1836 - mae: 50611.1836 - val_loss: 50778.3984 - val_mae: 50778.3984
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50461.9414 - mae: 50461.9414 - val_loss: 50713.6133 - val_mae: 50713.6133
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50373.5742 - mae: 50373.5742 - val_loss: 50670.9609 - val_mae: 50670.9609
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50305.1484 - mae: 50305.1484 - val_loss: 50635.5273 - val_mae: 50635.5273
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50245.1641 - mae: 50245.1641 - val_loss: 50596.7031 - val_mae: 50596.7031
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50192.5703 - mae: 50192.5703 - val_loss: 50575.6016 - val_mae: 50575.6016
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50141.9453 - mae: 50141.9453 - val_loss: 50543.3789 - val_mae: 50543.3789
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50100.9062 - mae: 50100.9062 - val_loss: 50520.0352 - val_mae: 50520.0352
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50061.6250 - mae: 50061.6250 - val_loss: 50499.0156 - val_mae: 50499.0156
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50024.1953 - mae: 50024.1953 - val_loss: 50478.2305 - val_mae: 50478.2305
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49986.3672 - mae: 49986.3672 - val_loss: 50455.0391 - val_mae: 50455.0391
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49952.6367 - mae: 49952.6367 - val_loss: 50433.1875 - val_mae: 50433.1875
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49922.5859 - mae: 49922.5859 - val_loss: 50414.1094 - val_mae: 50414.1094
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49894.3555 - mae: 49894.3555 - val_loss: 50406.1211 - val_mae: 50406.1211
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49865.7617 - mae: 49865.7617 - val_loss: 50395.1289 - val_mae: 50395.1289
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49842.4062 - mae: 49842.4062 - val_loss: 50385.0430 - val_mae: 50385.0430
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49819.1211 - mae: 49819.1211 - val_loss: 50377.7578 - val_mae: 50377.7578
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49798.8672 - mae: 49798.8672 - val_loss: 50359.0312 - val_mae: 50359.0312
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49779.7227 - mae: 49779.7227 - val_loss: 50342.3789 - val_mae: 50342.3789
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49759.9688 - mae: 49759.9688 - val_loss: 50327.3047 - val_mae: 50327.3047
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49741.2422 - mae: 49741.2422 - val_loss: 50316.1445 - val_mae: 50316.1445
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49723.0156 - mae: 49723.0156 - val_loss: 50302.0430 - val_mae: 50302.0430
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49708.0078 - mae: 49708.0078 - val_loss: 50299.0586 - val_mae: 50299.0586
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49693.2422 - mae: 49693.2422 - val_loss: 50296.0508 - val_mae: 50296.0508
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49677.9883 - mae: 49677.9883 - val_loss: 50282.1758 - val_mae: 50282.1758
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49667.2031 - mae: 49667.2031 - val_loss: 50283.9414 - val_mae: 50283.9414
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49653.1953 - mae: 49653.1953 - val_loss: 50268.0078 - val_mae: 50268.0078
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49640.4727 - mae: 49640.4727 - val_loss: 50261.7969 - val_mae: 50261.7969
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49632.1094 - mae: 49632.1094 - val_loss: 50255.5547 - val_mae: 50255.5547
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49616.0664 - mae: 49616.0664 - val_loss: 50252.7305 - val_mae: 50252.7305
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49604.6914 - mae: 49604.6914 - val_loss: 50256.4805 - val_mae: 50256.4805
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49595.0781 - mae: 49595.0781 - val_loss: 50260.3789 - val_mae: 50260.3789
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49583.8281 - mae: 49583.8281 - val_loss: 50250.0938 - val_mae: 50250.0938
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49574.7773 - mae: 49574.7773 - val_loss: 50246.7461 - val_mae: 50246.7461
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49564.3203 - mae: 49564.3203 - val_loss: 50231.8164 - val_mae: 50231.8164
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49555.8633 - mae: 49555.8633 - val_loss: 50237.7266 - val_mae: 50237.7266
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49546.2344 - mae: 49546.2344 - val_loss: 50234.2031 - val_mae: 50234.2031
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49533.9609 - mae: 49533.9609 - val_loss: 50232.3477 - val_mae: 50232.3477
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49526.5391 - mae: 49526.5391 - val_loss: 50232.0039 - val_mae: 50232.0039
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49518.5000 - mae: 49518.5000 - val_loss: 50237.2070 - val_mae: 50237.2070
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49510.9961 - mae: 49510.9961 - val_loss: 50230.1992 - val_mae: 50230.1992
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49503.2891 - mae: 49503.2891 - val_loss: 50229.1094 - val_mae: 50229.1094
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49496.6172 - mae: 49496.6172 - val_loss: 50224.1914 - val_mae: 50224.1914
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49489.2812 - mae: 49489.2812 - val_loss: 50235.9844 - val_mae: 50235.9844
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49483.1094 - mae: 49483.1094 - val_loss: 50237.9922 - val_mae: 50237.9922
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49477.8086 - mae: 49477.8086 - val_loss: 50241.0078 - val_mae: 50241.0078
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49469.4609 - mae: 49469.4609 - val_loss: 50242.1797 - val_mae: 50242.1797
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49461.6680 - mae: 49461.6680 - val_loss: 50240.2578 - val_mae: 50240.2578
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49458.3867 - mae: 49458.3867 - val_loss: 50244.2188 - val_mae: 50244.2188
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49450.6445 - mae: 49450.6445 - val_loss: 50236.3594 - val_mae: 50236.3594
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49447.5508 - mae: 49447.5508 - val_loss: 50235.1016 - val_mae: 50235.1016
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49440.6719 - mae: 49440.6719 - val_loss: 50239.5195 - val_mae: 50239.5195
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49433.8320 - mae: 49433.8320 - val_loss: 50240.5586 - val_mae: 50240.5586

In [17]:
model.save('artifacts/regression/regression_model.keras')

In [18]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regression_logs/fit

Reusing TensorBoard on port 6006 (pid 12856), started 0:00:03 ago. (Use '!kill 12856' to kill it.)